/*
 *     Name :  Iman Syahputra Situmorang
 *     NIM  :  11113064
 *     Date :  16/December/2014
 
 */
package View;

import Controller.DBManager;
import Model.Account;
import Model.Item;
import Model.Monster;
import Model.MonsterAccount;
import Model.MonsterItem;
import Model.TemplateMonsterTable;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Takiya
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private JFrame previousFrame;
    private boolean isPlayer1Ready = false;
    private boolean isPlayer2Ready = false;
    private DBManager manager;
    private Account AkunPlayer1 = null;
    private Account AkunPlayer2 = null;
    private MonsterAccount akunMonster1;
    private MonsterAccount akunMonster2;
    private Image imageBg;

    public Dashboard() {

        setUndecorated(true);
        imageBg = new ImageIcon(getClass().getResource("/Images/Background/iddle.png")).getImage();
        manager = new DBManager();
        initComponents();

        AfterStartMatch1.setVisible(false);
        AfterStartMatch2.setVisible(false);
        AfterStartMatch1.setOpaque(false);
        AfterStartMatch2.setOpaque(false);
        Panel_Player1.setOpaque(false);
        Panel_Player2.setOpaque(false);
        Vs_Panel.setOpaque(false);

        if (clip == null) {
            loadSound();

        } else {
            clip.stop();
            loadSound();
        }

    }

    AudioClip clip = null;

    public void loadSound() {

        URL url = getClass().getResource("/Sound/Dashboard1.wav");
        clip = Applet.newAudioClip(url);
//        AudioClip clip2 = Applet.newAudioClip(url);
        clip.play();
        clip.loop();
    }

    public void setPreviousFrame(JFrame _previousFrame) {
        this.previousFrame = _previousFrame;
    }

    public JFrame getPreviousFrame() {
        return this.previousFrame;
    }

    public void setAkun1(Account akun) {
        this.AkunPlayer1 = akun;
    }

    public void setAkun2(Account akun) {
        this.AkunPlayer2 = akun;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new PanelBackground(imageBg);
        ;
        Vs_Panel = new javax.swing.JPanel();
        lbl_Versus = new javax.swing.JLabel();
        Panel_Player1 = new javax.swing.JPanel();
        welcome_1 = new javax.swing.JLabel();
        monsterName1 = new javax.swing.JLabel();
        lbl_HP1 = new javax.swing.JLabel();
        lbl_AP1 = new javax.swing.JLabel();
        lbl_DP1 = new javax.swing.JLabel();
        lbl_Points1 = new javax.swing.JLabel();
        lbl_level1 = new javax.swing.JLabel();
        AP1 = new javax.swing.JLabel();
        DP1 = new javax.swing.JLabel();
        HP1 = new javax.swing.JLabel();
        Points1 = new javax.swing.JLabel();
        Level1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Item1 = new javax.swing.JTable();
        Update1 = new javax.swing.JLabel();
        BuyItem1 = new javax.swing.JLabel();
        lbl_Item1 = new javax.swing.JLabel();
        StartMatch1 = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        lbl_Coins3 = new javax.swing.JLabel();
        Coins1 = new javax.swing.JLabel();
        AfterStartMatch1 = new javax.swing.JPanel();
        lblMessage1 = new javax.swing.JLabel();
        loading1 = new javax.swing.JLabel();
        line1 = new javax.swing.JLabel();
        lbl_Versus1 = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();
        AfterStartMatch2 = new javax.swing.JPanel();
        lblMessage2 = new javax.swing.JLabel();
        loading2 = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        lbl_Versus2 = new javax.swing.JLabel();
        back2 = new javax.swing.JLabel();
        Panel_Player2 = new javax.swing.JPanel();
        welcome_2 = new javax.swing.JLabel();
        monsterName2 = new javax.swing.JLabel();
        lbl_HP2 = new javax.swing.JLabel();
        lbl_AP2 = new javax.swing.JLabel();
        lbl_DP2 = new javax.swing.JLabel();
        lbl_Points2 = new javax.swing.JLabel();
        lbl_Level2 = new javax.swing.JLabel();
        AP2 = new javax.swing.JLabel();
        DP2 = new javax.swing.JLabel();
        HP2 = new javax.swing.JLabel();
        Points2 = new javax.swing.JLabel();
        Level2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Item2 = new javax.swing.JTable();
        Update2 = new javax.swing.JLabel();
        BuyItem2 = new javax.swing.JLabel();
        lbl_item2 = new javax.swing.JLabel();
        StartMatch2 = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();
        lbl_Coins2 = new javax.swing.JLabel();
        Coins2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        background.setPreferredSize(new java.awt.Dimension(1366, 768));

        Vs_Panel.setAutoscrolls(true);
        Vs_Panel.setName(""); // NOI18N

        lbl_Versus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Versus.setText("VS");

        javax.swing.GroupLayout Vs_PanelLayout = new javax.swing.GroupLayout(Vs_Panel);
        Vs_Panel.setLayout(Vs_PanelLayout);
        Vs_PanelLayout.setHorizontalGroup(
            Vs_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vs_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Versus)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Vs_PanelLayout.setVerticalGroup(
            Vs_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vs_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Versus)
                .addGap(20, 20, 20))
        );

        Panel_Player1.setPreferredSize(new java.awt.Dimension(600, 686));

        welcome_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome_1.setForeground(new java.awt.Color(255, 102, 0));
        welcome_1.setText("Welcome ");

        monsterName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monsterName1.setForeground(new java.awt.Color(255, 102, 0));
        monsterName1.setText("Monster Name");

        lbl_HP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_HP1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_HP1.setText("HP");

        lbl_AP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_AP1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AP1.setText("AP");

        lbl_DP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DP1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DP1.setText("DP");

        lbl_Points1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Points1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Points1.setText("Points");

        lbl_level1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_level1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_level1.setText("Level");

        AP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AP1.setForeground(new java.awt.Color(255, 255, 255));
        AP1.setText("0");

        DP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DP1.setForeground(new java.awt.Color(255, 255, 255));
        DP1.setText("0");

        HP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HP1.setForeground(new java.awt.Color(255, 255, 255));
        HP1.setText("0");

        Points1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Points1.setForeground(new java.awt.Color(255, 255, 255));
        Points1.setText("0");

        Level1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Level1.setForeground(new java.awt.Color(255, 255, 255));
        Level1.setText("0");

        Item1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Item1);

        Update1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Update1.setForeground(new java.awt.Color(255, 255, 255));
        Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/updateMonster.png"))); // NOI18N
        Update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update1MouseClicked(evt);
            }
        });

        BuyItem1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BuyItem1.setForeground(new java.awt.Color(255, 255, 255));
        BuyItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/buy.png"))); // NOI18N
        BuyItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyItem1MouseClicked(evt);
            }
        });

        lbl_Item1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Item1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Item1.setText("My Item");

        StartMatch1.setText("Start Match");
        StartMatch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartMatch1ActionPerformed(evt);
            }
        });

        lbl_Coins3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Coins3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Coins3.setText("Coins");

        Coins1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Coins1.setForeground(new java.awt.Color(255, 255, 255));
        Coins1.setText("0");

        javax.swing.GroupLayout Panel_Player1Layout = new javax.swing.GroupLayout(Panel_Player1);
        Panel_Player1.setLayout(Panel_Player1Layout);
        Panel_Player1Layout.setHorizontalGroup(
            Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Player1Layout.createSequentialGroup()
                .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Player1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Player1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_Player1Layout.createSequentialGroup()
                                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_AP1)
                                            .addComponent(lbl_DP1)
                                            .addComponent(lbl_HP1)
                                            .addComponent(lbl_Points1)
                                            .addComponent(lbl_level1)
                                            .addComponent(lbl_Coins3))
                                        .addGap(80, 80, 80)
                                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Coins1)
                                            .addComponent(Level1)
                                            .addComponent(Points1)
                                            .addComponent(HP1)
                                            .addComponent(DP1)
                                            .addComponent(AP1)))
                                    .addComponent(Update1)))
                            .addGroup(Panel_Player1Layout.createSequentialGroup()
                                .addComponent(welcome_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monsterName1))))
                    .addGroup(Panel_Player1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StartMatch1)
                            .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Item1)
                                .addComponent(BuyItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        Panel_Player1Layout.setVerticalGroup(
            Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Player1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcome_1)
                    .addComponent(monsterName1))
                .addGap(44, 44, 44)
                .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Player1Layout.createSequentialGroup()
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_AP1)
                            .addComponent(AP1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_DP1)
                            .addComponent(DP1))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_HP1)
                            .addComponent(HP1))
                        .addGap(38, 38, 38)
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Points1)
                            .addComponent(Points1))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Coins3)
                            .addComponent(Coins1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_level1)
                            .addComponent(Level1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Update1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbl_Item1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuyItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(StartMatch1)
                .addGap(87, 87, 87))
        );

        lblMessage1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMessage1.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage1.setText("Waiting for Player 2");

        loading1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/36.gif"))); // NOI18N

        line1.setText("==========================");

        lbl_Versus1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Versus1.setText("VS");

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/Back1.png"))); // NOI18N
        back1.setText("Back");
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AfterStartMatch1Layout = new javax.swing.GroupLayout(AfterStartMatch1);
        AfterStartMatch1.setLayout(AfterStartMatch1Layout);
        AfterStartMatch1Layout.setHorizontalGroup(
            AfterStartMatch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterStartMatch1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(AfterStartMatch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AfterStartMatch1Layout.createSequentialGroup()
                        .addGroup(AfterStartMatch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage1)
                            .addComponent(line1))
                        .addContainerGap(298, Short.MAX_VALUE))
                    .addGroup(AfterStartMatch1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(loading1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Versus1))))
            .addGroup(AfterStartMatch1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AfterStartMatch1Layout.setVerticalGroup(
            AfterStartMatch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterStartMatch1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblMessage1)
                .addGroup(AfterStartMatch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AfterStartMatch1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(loading1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfterStartMatch1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Versus1)
                        .addGap(1, 1, 1)))
                .addComponent(line1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back1)
                .addGap(31, 31, 31))
        );

        lblMessage2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMessage2.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage2.setText("Waiting for Player 1");

        loading2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/36.gif"))); // NOI18N

        line2.setText("==========================");

        lbl_Versus2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Versus2.setText("VS");

        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/Next.png"))); // NOI18N
        back2.setText("Back");
        back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AfterStartMatch2Layout = new javax.swing.GroupLayout(AfterStartMatch2);
        AfterStartMatch2.setLayout(AfterStartMatch2Layout);
        AfterStartMatch2Layout.setHorizontalGroup(
            AfterStartMatch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterStartMatch2Layout.createSequentialGroup()
                .addComponent(lbl_Versus2)
                .addGap(141, 141, 141)
                .addGroup(AfterStartMatch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AfterStartMatch2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(loading2))
                    .addComponent(lblMessage2)
                    .addComponent(line2))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfterStartMatch2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back2)
                .addGap(18, 18, 18))
        );
        AfterStartMatch2Layout.setVerticalGroup(
            AfterStartMatch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterStartMatch2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblMessage2)
                .addGap(18, 18, 18)
                .addComponent(loading2)
                .addGroup(AfterStartMatch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AfterStartMatch2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(line2))
                    .addGroup(AfterStartMatch2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Versus2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(back2)
                .addContainerGap())
        );

        Panel_Player2.setPreferredSize(new java.awt.Dimension(600, 686));

        welcome_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome_2.setForeground(new java.awt.Color(255, 102, 0));
        welcome_2.setText("Welcome ");

        monsterName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monsterName2.setForeground(new java.awt.Color(255, 102, 0));
        monsterName2.setText("Monster Name");

        lbl_HP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_HP2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_HP2.setText("HP");

        lbl_AP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_AP2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AP2.setText("AP");

        lbl_DP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DP2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DP2.setText("DP");

        lbl_Points2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Points2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Points2.setText("Points");

        lbl_Level2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Level2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Level2.setText("Level");

        AP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AP2.setForeground(new java.awt.Color(255, 255, 255));
        AP2.setText("0");

        DP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DP2.setForeground(new java.awt.Color(255, 255, 255));
        DP2.setText("0");

        HP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HP2.setForeground(new java.awt.Color(255, 255, 255));
        HP2.setText("0");

        Points2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Points2.setForeground(new java.awt.Color(255, 255, 255));
        Points2.setText("0");

        Level2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Level2.setForeground(new java.awt.Color(255, 255, 255));
        Level2.setText("0");

        Item2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Item2);

        Update2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Update2.setForeground(new java.awt.Color(255, 255, 255));
        Update2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/updateMonster.png"))); // NOI18N
        Update2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update2MouseClicked(evt);
            }
        });

        BuyItem2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BuyItem2.setForeground(new java.awt.Color(255, 255, 255));
        BuyItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/buy.png"))); // NOI18N
        BuyItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyItem2MouseClicked(evt);
            }
        });

        lbl_item2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_item2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_item2.setText("My Item");

        StartMatch2.setText("Start Match");
        StartMatch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartMatch2ActionPerformed(evt);
            }
        });

        lbl_Coins2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Coins2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Coins2.setText("Coins");

        Coins2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Coins2.setForeground(new java.awt.Color(255, 255, 255));
        Coins2.setText("0");

        javax.swing.GroupLayout Panel_Player2Layout = new javax.swing.GroupLayout(Panel_Player2);
        Panel_Player2.setLayout(Panel_Player2Layout);
        Panel_Player2Layout.setHorizontalGroup(
            Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Player2Layout.createSequentialGroup()
                .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Player2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(welcome_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monsterName2))
                    .addGroup(Panel_Player2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StartMatch2)
                            .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_item2)
                                .addComponent(BuyItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_Player2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Player2Layout.createSequentialGroup()
                                .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_AP2)
                                    .addComponent(lbl_DP2)
                                    .addComponent(lbl_HP2)
                                    .addComponent(lbl_Points2)
                                    .addComponent(lbl_Level2)
                                    .addComponent(lbl_Coins2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Level2)
                                    .addComponent(Points2)
                                    .addComponent(HP2)
                                    .addComponent(DP2)
                                    .addComponent(AP2)
                                    .addComponent(Coins2))
                                .addGap(106, 106, 106))
                            .addGroup(Panel_Player2Layout.createSequentialGroup()
                                .addComponent(Update2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Panel_Player2Layout.setVerticalGroup(
            Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Player2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcome_2)
                    .addComponent(monsterName2))
                .addGap(36, 36, 36)
                .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Player2Layout.createSequentialGroup()
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_AP2)
                            .addComponent(AP2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_DP2)
                            .addComponent(DP2))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_HP2)
                            .addComponent(HP2))
                        .addGap(38, 38, 38)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Points2)
                            .addComponent(Points2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Coins2)
                            .addComponent(Coins2))
                        .addGap(13, 13, 13)
                        .addGroup(Panel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Level2)
                            .addComponent(Level2))
                        .addGap(18, 18, 18)
                        .addComponent(Update2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(image2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(lbl_item2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BuyItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(StartMatch2)
                .addGap(77, 77, 77))
        );

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/icons_sound.png"))); // NOI18N
        sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Panel_Player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Vs_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Panel_Player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(AfterStartMatch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(740, Short.MAX_VALUE)))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addContainerGap(742, Short.MAX_VALUE)
                    .addComponent(AfterStartMatch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(Vs_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sound)
                            .addComponent(exit))
                        .addGap(13, 13, 13)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel_Player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_Player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(AfterStartMatch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(323, Short.MAX_VALUE)))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(AfterStartMatch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartMatch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartMatch1ActionPerformed
        // TODO add your handling code here:

        int choose = JOptionPane.showConfirmDialog(this, "Start Match?");
        if (choose == 0) {
            isPlayer1Ready = true;
            Panel_Player1.setVisible(false);
            AfterStartMatch1.setVisible(true);
            Vs_Panel.setVisible(false);
        }

        if (isPlayer1Ready && isPlayer2Ready) {
            // new Match here

            Battle btel = new Battle();

            btel.setAkunPlayer1(AkunPlayer1);
            btel.setAkunPlayer2(AkunPlayer2);

            btel.setVisible(true);
            btel.setIsRun(true);
            new Thread(btel).start();
            btel.setVisible(true);

            btel.setPreviousFrame(this);
            this.setVisible(false);
        clip.stop();
        }


    }//GEN-LAST:event_StartMatch1ActionPerformed

    private void StartMatch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartMatch2ActionPerformed
        // TODO add your handling code here:

        int choose = JOptionPane.showConfirmDialog(this, "Start Match?");
        if (choose == 0) {

            isPlayer2Ready = true;
            Panel_Player2.setVisible(false);
            AfterStartMatch2.setVisible(true);
            Vs_Panel.setVisible(false);
        }

        if (isPlayer1Ready && isPlayer2Ready) {
            // new Match here
            Battle btel = new Battle();
            btel.setAkunPlayer1(AkunPlayer1);
            btel.setAkunPlayer2(AkunPlayer2);

            btel.setVisible(true);
            btel.setIsRun(true);
            new Thread(btel).start();
            btel.setVisible(true);

            btel.setPreviousFrame(this);
            this.setVisible(false);
            clip.stop();
        }

    }//GEN-LAST:event_StartMatch2ActionPerformed

    private void back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseClicked
        // TODO add your handling code here:
        isPlayer2Ready = false;
        Panel_Player2.setVisible(true);
        AfterStartMatch2.setVisible(false);
        Vs_Panel.setVisible(true);
    }//GEN-LAST:event_back2MouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        // TODO add your handling code here:
        isPlayer1Ready = false;
        Panel_Player1.setVisible(true);
        AfterStartMatch1.setVisible(false);
        Vs_Panel.setVisible(true);
    }//GEN-LAST:event_back1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadStats();
        loadData();
       
//        if (clip == null) {
//            loadSound();

//        } else {
            clip.stop();
            loadSound();
//        }
        
    }//GEN-LAST:event_formWindowActivated

    public void loadStats() {

        // TODO add your handling code here:
//        AkunPlayer1 = manager.getAccountByUsername("iman");
//        AkunPlayer2 = manager.getAccountByUsername("veni");
//        previousFrame.setVisible(false);
        akunMonster1 = manager.getAkunMonsterbyUser(AkunPlayer1.getId());
        akunMonster2 = manager.getAkunMonsterbyUser(AkunPlayer2.getId());
//        akunMonster1 = manager.getAkunMonsterbyUser(1);
//        akunMonster2 = manager.getAkunMonsterbyUser(2);
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/Images/Monster/" + akunMonster1.getMonsterId().getAvatarUrl()));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/Images/Monster/" + akunMonster2.getMonsterId().getAvatarUrl()));

        //image
        image1.setIcon(icon1);
        image2.setIcon(icon2);
        //name monster
        monsterName1.setText(akunMonster1.getAccountId().getUsername());
        monsterName2.setText(akunMonster2.getAccountId().getUsername());
        //HP
        HP1.setText(new Integer(akunMonster1.getHp()).toString());
        HP2.setText(new Integer(akunMonster2.getHp()).toString());
        //DP
        DP1.setText(new Integer(akunMonster1.getDp()).toString());
        DP2.setText(new Integer(akunMonster2.getDp()).toString());
        //AP
        AP1.setText(new Integer(akunMonster1.getAp()).toString());
        AP2.setText(new Integer(akunMonster2.getAp()).toString());
        //Level
        Level1.setText(new Integer(akunMonster1.getLevel()).toString());
        Level2.setText(new Integer(akunMonster2.getLevel()).toString());
        //Points
        Points1.setText(new Integer(akunMonster1.getWinPoint()).toString());
        Points2.setText(new Integer(akunMonster2.getWinPoint()).toString());
        //Coints
        Coins1.setText(new Integer(akunMonster1.getCoin()).toString());
        Coins2.setText(new Integer(akunMonster2.getCoin()).toString());

    }

    public void loadData() {
        Object[] coloumnNames = {"Item", "Name", "AP", "DP", "HP"};
        ArrayList<MonsterItem> itemM = new ArrayList<MonsterItem>();
        ArrayList<MonsterItem> itemM1 = new ArrayList<MonsterItem>();
        itemM = manager.loadItemMonster(akunMonster1.getId());
        itemM1 = manager.loadItemMonster(akunMonster2.getId());
        ArrayList<ImageIcon> item1 = new ArrayList<ImageIcon>();
        ArrayList<ImageIcon> item2 = new ArrayList<ImageIcon>();

        int numOfItem = itemM.size();
        int numOfItem1 = itemM1.size();

//        if (numOfItem > 0) {

        for (int i = 0; i < numOfItem; i++) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/Item/" + itemM.get(i).getItem().getAvatarUrl()));
            item1.add(icon);
//        }
        }
        
//        if (numOfItem1 > 0) {

        for (int i = 0; i < numOfItem1; i++) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/Item/" + itemM1.get(i).getItem().getAvatarUrl()));
            item2.add(icon);
        }
//        }
        


        Object data[][] = new Object[numOfItem][5];
        Object data1[][] = new Object[numOfItem1][5];

//        if (numOfItem > 0) {

            for (int i = 0; i < numOfItem; i++) {
                data[i][0] = item1.get(i);
                data[i][1] = itemM.get(i).getItem().getName();
                data[i][2] = itemM.get(i).getItem().getAp();
                data[i][3] = itemM.get(i).getItem().getDp();
                data[i][4] = itemM.get(i).getItem().getHp();

            }
//        }
//        if (numOfItem1 > 0) {
            for (int i = 0; i < numOfItem1; i++) {
                data1[i][0] = item2.get(i);
                data1[i][1] = itemM1.get(i).getItem().getName();
                data1[i][2] = itemM1.get(i).getItem().getAp();
                data1[i][3] = itemM1.get(i).getItem().getDp();
                data1[i][4] = itemM1.get(i).getItem().getHp();
            }
//        }
        TemplateMonsterTable dtTable = new TemplateMonsterTable(data, coloumnNames);
        TemplateMonsterTable dtTable1 = new TemplateMonsterTable(data1, coloumnNames);
        this.Item1.setModel(dtTable);
        this.Item2.setModel(dtTable1);
        this.Item1.setRowHeight(30);
        this.Item2.setRowHeight(30);
    }

    private void UpdateStats(Account akun) {
        Edit_stats edit = new Edit_stats();
        edit.setPreviousFrame(this);
        edit.setAkun(akun);
        edit.setVisible(true);

        this.setVisible(false);
    }

    private void buyNewItem(MonsterAccount akun, Account akunUtama) {
        BuyItem buy = new BuyItem();
        buy.setPreviousFrame(this);
        buy.setAccount(akunUtama);
        buy.setMonsterAccount(akun);
        buy.setVisible(true);

        this.setVisible(false);
    }


    private void Update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update1MouseClicked
                clip.stop();

        UpdateStats(AkunPlayer1);

    }//GEN-LAST:event_Update1MouseClicked

    private void Update2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update2MouseClicked
                        clip.stop();

        UpdateStats(AkunPlayer2);
                clip.stop();

    }//GEN-LAST:event_Update2MouseClicked

    private void BuyItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyItem1MouseClicked
        clip.stop();

        buyNewItem(akunMonster1, AkunPlayer1);
    }//GEN-LAST:event_BuyItem1MouseClicked

    private void BuyItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyItem2MouseClicked
        buyNewItem(akunMonster2, AkunPlayer2);
        clip.stop();

    }//GEN-LAST:event_BuyItem2MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked
    int suaraControl = 0;
    private void soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soundMouseClicked
        // TODO add your handling code here:
        suaraControl++;

        if (suaraControl % 2 != 0) {
            clip.stop();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icon_x.png")));
        } else {
            loadSound();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icons_sound.png")));
        }
    }//GEN-LAST:event_soundMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AP1;
    private javax.swing.JLabel AP2;
    private javax.swing.JPanel AfterStartMatch1;
    private javax.swing.JPanel AfterStartMatch2;
    private javax.swing.JLabel BuyItem1;
    private javax.swing.JLabel BuyItem2;
    private javax.swing.JLabel Coins1;
    private javax.swing.JLabel Coins2;
    private javax.swing.JLabel DP1;
    private javax.swing.JLabel DP2;
    private javax.swing.JLabel HP1;
    private javax.swing.JLabel HP2;
    private javax.swing.JTable Item1;
    private javax.swing.JTable Item2;
    private javax.swing.JLabel Level1;
    private javax.swing.JLabel Level2;
    private javax.swing.JPanel Panel_Player1;
    private javax.swing.JPanel Panel_Player2;
    private javax.swing.JLabel Points1;
    private javax.swing.JLabel Points2;
    private javax.swing.JButton StartMatch1;
    private javax.swing.JButton StartMatch2;
    private javax.swing.JLabel Update1;
    private javax.swing.JLabel Update2;
    private javax.swing.JPanel Vs_Panel;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel back2;
    private javax.swing.JPanel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessage1;
    private javax.swing.JLabel lblMessage2;
    private javax.swing.JLabel lbl_AP1;
    private javax.swing.JLabel lbl_AP2;
    private javax.swing.JLabel lbl_Coins2;
    private javax.swing.JLabel lbl_Coins3;
    private javax.swing.JLabel lbl_DP1;
    private javax.swing.JLabel lbl_DP2;
    private javax.swing.JLabel lbl_HP1;
    private javax.swing.JLabel lbl_HP2;
    private javax.swing.JLabel lbl_Item1;
    private javax.swing.JLabel lbl_Level2;
    private javax.swing.JLabel lbl_Points1;
    private javax.swing.JLabel lbl_Points2;
    private javax.swing.JLabel lbl_Versus;
    private javax.swing.JLabel lbl_Versus1;
    private javax.swing.JLabel lbl_Versus2;
    private javax.swing.JLabel lbl_item2;
    private javax.swing.JLabel lbl_level1;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JLabel loading1;
    private javax.swing.JLabel loading2;
    private javax.swing.JLabel monsterName1;
    private javax.swing.JLabel monsterName2;
    private javax.swing.JLabel sound;
    private javax.swing.JLabel welcome_1;
    private javax.swing.JLabel welcome_2;
    // End of variables declaration//GEN-END:variables

}
