/*
 *     Name :  Iman Syahputra Situmorang
 *     NIM  :  11113064
 *     Date :  12/December/2014
 
 */
package View;

import Controller.DBManager;
import Model.Account;
import Model.MonsterAccount;
import Model.MonsterItem;
import Model.TemplateMonsterTable;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Takiya
 */
public class Edit_stats extends javax.swing.JFrame {

    /**
     * Creates new form Iddle
     */
    private MonsterAccount akunMonster;
    private Account akun;
    private Image image;
    private JFrame previousFrame;
    private DBManager manager;

    public Edit_stats() {

        setUndecorated(true);
        image = new ImageIcon(getClass().getResource("/Images/Background/LadyDark.jpg")).getImage();
        manager = new DBManager();
//        previousFrame.setVisible(false);
        initComponents();

        if (clip == null) {
            loadSound();

        } else {
            clip.stop();
            loadSound();
        }

    }

    AudioClip clip = null;

    
    public void loadSound() {

        URL url = getClass().getResource("/Sound/Dashboard.wav");
        clip = Applet.newAudioClip(url);
//        AudioClip clip2 = Applet.newAudioClip(url);
        clip.play();
        clip.loop();
    }

    public void setPreviousFrame(JFrame frame) {
        this.previousFrame = frame;
    }

    public void setAkun(Account akun) {
        this.akun = akun;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadData() {

//        akun = manager.getAccountByUsername("love");
//        System.out.println(akun.getUsername());
//        System.out.println(akun.getId());
        akunMonster = manager.getAkunMonsterbyUser(akun.getId());
        monsterName1.setText(akunMonster.getAccountId().getUsername());
        String hp = (new Integer(akunMonster.getHp())).toString();
        String ap = (new Integer(akunMonster.getAp())).toString();
        String dp = (new Integer(akunMonster.getDp())).toString();
        String level = (new Integer(akunMonster.getLevel())).toString();
        String winPoint = (new Integer(akunMonster.getWinPoint())).toString();
        String gambar = akunMonster.getMonsterId().getAvatarUrl();
        AP1.setText(ap);
        HP1.setText(hp);
        DP1.setText(dp);
        Level1.setText(level);
        Point1.setText(winPoint);
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Monster/" + gambar)));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new PanelBackground(image);
        ;
        lblWelcome1 = new javax.swing.JLabel();
        monsterName1 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        lblHp1 = new javax.swing.JLabel();
        HP1 = new javax.swing.JLabel();
        lblAp1 = new javax.swing.JLabel();
        AP1 = new javax.swing.JLabel();
        DP1 = new javax.swing.JLabel();
        lblDP1 = new javax.swing.JLabel();
        Level1 = new javax.swing.JLabel();
        lblLevel1 = new javax.swing.JLabel();
        lblPoint1 = new javax.swing.JLabel();
        Point1 = new javax.swing.JLabel();
        addAp1 = new javax.swing.JButton();
        addHp1 = new javax.swing.JButton();
        addDp1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemMonster = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setPreferredSize(new java.awt.Dimension(1366, 768));

        lblWelcome1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome1.setText("Welcome");

        monsterName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        monsterName1.setForeground(new java.awt.Color(255, 255, 255));
        monsterName1.setText("Monster Name");

        image1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        image1.setForeground(new java.awt.Color(255, 255, 255));
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Monster/Djinn.png"))); // NOI18N

        lblHp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHp1.setForeground(new java.awt.Color(255, 255, 255));
        lblHp1.setText("HP");

        HP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HP1.setForeground(new java.awt.Color(255, 255, 255));
        HP1.setText("0");

        lblAp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAp1.setForeground(new java.awt.Color(255, 255, 255));
        lblAp1.setText("AP");

        AP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AP1.setForeground(new java.awt.Color(255, 255, 255));
        AP1.setText("0");

        DP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DP1.setForeground(new java.awt.Color(255, 255, 255));
        DP1.setText("0");

        lblDP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDP1.setForeground(new java.awt.Color(255, 255, 255));
        lblDP1.setText("DP");

        Level1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Level1.setForeground(new java.awt.Color(255, 255, 255));
        Level1.setText("0");

        lblLevel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLevel1.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel1.setText("Level");

        lblPoint1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPoint1.setForeground(new java.awt.Color(255, 255, 255));
        lblPoint1.setText("Point");

        Point1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Point1.setForeground(new java.awt.Color(255, 255, 255));
        Point1.setText("0");

        addAp1.setText("+");
        addAp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAp1ActionPerformed(evt);
            }
        });

        addHp1.setText("+");
        addHp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHp1ActionPerformed(evt);
            }
        });

        addDp1.setText("+");
        addDp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDp1ActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/back.png"))); // NOI18N
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        itemMonster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(itemMonster);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Item");

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/icons_sound.png"))); // NOI18N
        sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soundMouseClicked(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(lblPoint1)
                        .addGap(31, 31, 31)
                        .addComponent(Point1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(lblWelcome1)
                                .addGap(18, 18, 18)
                                .addComponent(monsterName1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(lblLevel1)
                                .addGap(31, 31, 31)
                                .addComponent(Level1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(lblHp1)
                                .addGap(52, 52, 52)
                                .addComponent(HP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(lblAp1)
                                .addGap(52, 52, 52)
                                .addComponent(AP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(lblDP1)
                                .addGap(52, 52, 52)
                                .addComponent(DP1)))
                        .addGap(35, 35, 35)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addDp1)
                                .addComponent(addAp1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(addHp1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sound)
                    .addComponent(exit))
                .addGap(25, 25, 25)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monsterName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHp1)
                            .addComponent(HP1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHp1))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAp1)
                            .addComponent(AP1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAp1))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDP1)
                            .addComponent(DP1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDp1)))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLevel1)
                    .addComponent(Level1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoint1)
                    .addComponent(Point1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadData();
        loadDataTableItem();
    }//GEN-LAST:event_formWindowActivated
    private void addHp() {
        int Point = akunMonster.getWinPoint();
        if (Point != 0) {
            int hp = akunMonster.getHp();
            hp++;
            Point--;
            akunMonster.setHp(hp);
            akunMonster.setWinPoint(Point);
            manager.updateMonsterAccount(akunMonster);

        } else {
            JOptionPane.showMessageDialog(this, "Point anda tidak mencukupi");
        }

    }

    private void addDp() {
        int Point = akunMonster.getWinPoint();
        if (Point != 0) {
            int dp = akunMonster.getDp();
            dp++;
            Point--;
            akunMonster.setDp(dp);
            akunMonster.setWinPoint(Point);
            manager.updateMonsterAccount(akunMonster);

        } else {
            JOptionPane.showMessageDialog(this, "Point anda tidak mencukupi");
        }

    }

    private void addAp() {
        int Point = akunMonster.getWinPoint();
        if (Point != 0) {
            int ap = akunMonster.getAp();
            ap++;
            Point--;
            akunMonster.setAp(ap);
            akunMonster.setWinPoint(Point);
            manager.updateMonsterAccount(akunMonster);

        } else {
            JOptionPane.showMessageDialog(this, "Point anda tidak mencukupi");
        }

    }


    private void addHp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHp1ActionPerformed
        // TODO add your handling code here:
        addHp();
        loadData();
    }//GEN-LAST:event_addHp1ActionPerformed

    private void addAp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAp1ActionPerformed
        // TODO add your handling code here:
        addAp();
        loadData();
    }//GEN-LAST:event_addAp1ActionPerformed

    private void addDp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDp1ActionPerformed
        // TODO add your handling code here:
        addDp();
        loadData();
    }//GEN-LAST:event_addDp1ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        previousFrame.setVisible(true);
        this.setVisible(false);
        clip.stop();
    }//GEN-LAST:event_backMouseClicked
    private int suaraControl = 0;
    private void soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soundMouseClicked
        // TODO add your handling code here:
        suaraControl++;

        if (suaraControl % 2 != 0) {
            clip.stop();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icon_x.png")));
        } else {
            loadSound();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icons_sound.png")));
        }
    }//GEN-LAST:event_soundMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    public void loadDataTableItem() {
        Object[] coloumnNames = {"Item", "Name", "AP", "DP", "HP"};
        ArrayList<MonsterItem> itemM = new ArrayList<MonsterItem>();

        itemM = manager.loadItemMonster(akunMonster.getId());

        ArrayList<ImageIcon> item1 = new ArrayList<ImageIcon>();
        ArrayList<ImageIcon> item2 = new ArrayList<ImageIcon>();

        int numOfItem = itemM.size();

        for (int i = 0; i < numOfItem; i++) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/Item/" + itemM.get(i).getItem().getAvatarUrl()));
            item1.add(icon);
        }

        Object data[][] = new Object[numOfItem][5];

        for (int i = 0; i < numOfItem; i++) {
            data[i][0] = item1.get(i);
            data[i][1] = itemM.get(i).getItem().getName();
            data[i][2] = itemM.get(i).getItem().getAp();
            data[i][3] = itemM.get(i).getItem().getDp();
            data[i][4] = itemM.get(i).getItem().getHp();

        }

        TemplateMonsterTable dtTable = new TemplateMonsterTable(data, coloumnNames);

        this.itemMonster.setModel(dtTable);

        this.itemMonster.setRowHeight(30);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AP1;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel DP1;
    private javax.swing.JLabel HP1;
    private javax.swing.JLabel Level1;
    private javax.swing.JLabel Point1;
    private javax.swing.JButton addAp1;
    private javax.swing.JButton addDp1;
    private javax.swing.JButton addHp1;
    private javax.swing.JLabel back;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel image1;
    private javax.swing.JTable itemMonster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAp1;
    private javax.swing.JLabel lblDP1;
    private javax.swing.JLabel lblHp1;
    private javax.swing.JLabel lblLevel1;
    private javax.swing.JLabel lblPoint1;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel monsterName1;
    private javax.swing.JLabel sound;
    // End of variables declaration//GEN-END:variables
}
