/*
 *     Name :  Iman Syahputra Situmorang
 *     NIM  :  11113064
 *     Date :  09/December/2014
 
 */
package View;

import Controller.DBManager;
import Model.Account;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sun.audio.AudioData;
import sun.audio.AudioPlayer;

/**
 *
 * @author Takiya
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Image image = null;
    private boolean isPlayer1Login = false;
    private boolean isPlayer2Login = false;
    private String player1 = null;
    private String player2 = null;
    private JFrame previous;
    private DBManager manager = null;
    private Account akun1;
    private Account akun2;

    public Login() {

        setUndecorated(true);
        //previous.setVisible(false);
        manager = new DBManager();
        image = new ImageIcon(getClass().getResource("/Images/Background/login.png")).getImage();

        initComponents();

        background.setVisible(true);
        panellogin1.setVisible(true);
        panellogin2.setVisible(true);
        containerlogin1.setVisible(true);
        containerlogin2.setVisible(true);
        afterlogin1.setVisible(false);
        afterlogin2.setVisible(false);
        containerlogin1.setOpaque(false);
        containerlogin2.setOpaque(false);

//        username1.setFocusable(false);
//        username2.setFocusable(false);
//        pass1.setFocusable(false);
//        pass2.setFocusable(false);
//        
        panellogin1.setBackground(new Color(123, 134, 145, 83));
        panellogin2.setBackground(new Color(123, 134, 145, 83));

        if (clip == null) {
            loadSound();

        } else {
            clip.stop();
            loadSound();
        }
    }

    public void setPrevious(JFrame frame) {

        this.previous = frame;

    }

    public JFrame getPrevious() {

        return this.previous;

    }
    
    
    AudioClip clip;

    public void loadSound() {

        URL url = Login.class.getResource("/Sound/Main.wav");
        clip = Applet.newAudioClip(url);
//        AudioClip clip2 = Applet.newAudioClip(url);
        clip.play();
        clip.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new PanelBackground(image);  ;
        containerlogin1 = new javax.swing.JPanel();
        panellogin1 = new javax.swing.JPanel();
        lbl_player1 = new javax.swing.JLabel();
        lbl_user1 = new javax.swing.JLabel();
        lbl_pass1 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        login1 = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();
        NotifError_username1 = new javax.swing.JLabel();
        NotifError_pass1 = new javax.swing.JLabel();
        afterlogin1 = new javax.swing.JPanel();
        lblMessage1 = new javax.swing.JLabel();
        loading1 = new javax.swing.JLabel();
        line1 = new javax.swing.JLabel();
        containerlogin2 = new javax.swing.JPanel();
        panellogin2 = new javax.swing.JPanel();
        lbl_player2 = new javax.swing.JLabel();
        lbl_user2 = new javax.swing.JLabel();
        lbl_pass2 = new javax.swing.JLabel();
        username2 = new javax.swing.JTextField();
        login2 = new javax.swing.JButton();
        pass2 = new javax.swing.JPasswordField();
        NotifError_username2 = new javax.swing.JLabel();
        NotifError_pass2 = new javax.swing.JLabel();
        afterlogin2 = new javax.swing.JPanel();
        lblMessage2 = new javax.swing.JLabel();
        loading2 = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        lblNotAccount = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        background.setPreferredSize(new java.awt.Dimension(1366, 768));

        containerlogin1.setPreferredSize(new java.awt.Dimension(600, 400));

        lbl_player1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_player1.setText("Player 1");

        lbl_user1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_user1.setForeground(new java.awt.Color(255, 255, 51));
        lbl_user1.setText("Username");

        lbl_pass1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pass1.setForeground(new java.awt.Color(255, 255, 51));
        lbl_pass1.setText("Password");

        login1.setText("Login");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        NotifError_username1.setForeground(new java.awt.Color(255, 0, 0));
        NotifError_username1.setText(" ");

        NotifError_pass1.setForeground(new java.awt.Color(255, 0, 0));
        NotifError_pass1.setText(" ");

        javax.swing.GroupLayout panellogin1Layout = new javax.swing.GroupLayout(panellogin1);
        panellogin1.setLayout(panellogin1Layout);
        panellogin1Layout.setHorizontalGroup(
            panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogin1Layout.createSequentialGroup()
                .addGroup(panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellogin1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_player1))
                    .addGroup(panellogin1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panellogin1Layout.createSequentialGroup()
                                .addGroup(panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_user1)
                                    .addComponent(lbl_pass1))
                                .addGap(77, 77, 77)
                                .addGroup(panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NotifError_username1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(username1)
                                    .addComponent(pass1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(NotifError_pass1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        panellogin1Layout.setVerticalGroup(
            panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_player1)
                .addGap(70, 70, 70)
                .addGroup(panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_user1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NotifError_username1)
                .addGap(18, 18, 18)
                .addGroup(panellogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pass1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NotifError_pass1)
                .addGap(18, 18, 18)
                .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        lblMessage1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMessage1.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage1.setText("Waiting for Player 2");

        loading1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/36.gif"))); // NOI18N

        line1.setText("==========================");

        javax.swing.GroupLayout afterlogin1Layout = new javax.swing.GroupLayout(afterlogin1);
        afterlogin1.setLayout(afterlogin1Layout);
        afterlogin1Layout.setHorizontalGroup(
            afterlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterlogin1Layout.createSequentialGroup()
                .addGroup(afterlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterlogin1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(loading1))
                    .addGroup(afterlogin1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(afterlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage1)
                            .addComponent(line1))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        afterlogin1Layout.setVerticalGroup(
            afterlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterlogin1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblMessage1)
                .addGap(18, 18, 18)
                .addComponent(loading1)
                .addGap(28, 28, 28)
                .addComponent(line1)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerlogin1Layout = new javax.swing.GroupLayout(containerlogin1);
        containerlogin1.setLayout(containerlogin1Layout);
        containerlogin1Layout.setHorizontalGroup(
            containerlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerlogin1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(afterlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        containerlogin1Layout.setVerticalGroup(
            containerlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerlogin1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(afterlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        containerlogin2.setPreferredSize(new java.awt.Dimension(600, 400));

        lbl_player2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_player2.setText("Player 2");

        lbl_user2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_user2.setForeground(new java.awt.Color(255, 255, 51));
        lbl_user2.setText("Username");

        lbl_pass2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pass2.setForeground(new java.awt.Color(255, 255, 51));
        lbl_pass2.setText("Password");

        login2.setText("Login");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });

        NotifError_username2.setForeground(new java.awt.Color(255, 0, 0));
        NotifError_username2.setText(" ");

        NotifError_pass2.setForeground(new java.awt.Color(255, 0, 0));
        NotifError_pass2.setText(" ");

        javax.swing.GroupLayout panellogin2Layout = new javax.swing.GroupLayout(panellogin2);
        panellogin2.setLayout(panellogin2Layout);
        panellogin2Layout.setHorizontalGroup(
            panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogin2Layout.createSequentialGroup()
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellogin2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_player2))
                    .addGroup(panellogin2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panellogin2Layout.createSequentialGroup()
                                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_user2)
                                    .addComponent(lbl_pass2))
                                .addGap(77, 77, 77)
                                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NotifError_username2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(username2)
                                    .addComponent(pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(NotifError_pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        panellogin2Layout.setVerticalGroup(
            panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_player2)
                .addGap(70, 70, 70)
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_user2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NotifError_username2)
                .addGap(18, 18, 18)
                .addGroup(panellogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pass2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NotifError_pass2)
                .addGap(18, 18, 18)
                .addComponent(login2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        lblMessage2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMessage2.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage2.setText("Waiting for Player 1");

        loading2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/36.gif"))); // NOI18N

        line2.setText("==========================");

        javax.swing.GroupLayout afterlogin2Layout = new javax.swing.GroupLayout(afterlogin2);
        afterlogin2.setLayout(afterlogin2Layout);
        afterlogin2Layout.setHorizontalGroup(
            afterlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterlogin2Layout.createSequentialGroup()
                .addGroup(afterlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterlogin2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(loading2))
                    .addGroup(afterlogin2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(afterlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage2)
                            .addComponent(line2))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        afterlogin2Layout.setVerticalGroup(
            afterlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterlogin2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblMessage2)
                .addGap(18, 18, 18)
                .addComponent(loading2)
                .addGap(28, 28, 28)
                .addComponent(line2)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerlogin2Layout = new javax.swing.GroupLayout(containerlogin2);
        containerlogin2.setLayout(containerlogin2Layout);
        containerlogin2Layout.setHorizontalGroup(
            containerlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerlogin2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(afterlogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        containerlogin2Layout.setVerticalGroup(
            containerlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerlogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerlogin2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(afterlogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lbl_welcome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/header.png"))); // NOI18N

        lblNotAccount.setBackground(new java.awt.Color(0, 0, 255));
        lblNotAccount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNotAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblNotAccount.setText("I Have no Account");

        register.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/create.png"))); // NOI18N
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/icons_sound.png"))); // NOI18N
        sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(containerlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(containerlogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(lblNotAccount)
                        .addGap(518, 518, 518))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(register)
                        .addGap(573, 573, 573))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_welcome)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sound)
                        .addComponent(exit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(containerlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerlogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNotAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:

        if (username1.getText().equalsIgnoreCase(player2)) {
            JOptionPane.showMessageDialog(panellogin1, "Akun ini sudah di pakai oleh user lain");

        } else {

            String username = username1.getText();
            String password = new String(pass1.getPassword());

            akun1 = new Account();

            akun1 = manager.getAccountByUsername(username);

            if (akun1 == null) {
                JOptionPane.showMessageDialog(this, "Salah username");
                
                username1.setText("");
                pass1.setText("");
            } else {
                if (password.equals(akun1.getPassword())) {
                    isPlayer1Login = true;
                    player1 = username;

                    panellogin1.setVisible(false);
                    panellogin1.setOpaque(false);
                    afterlogin1.setVisible(true);
                    afterlogin1.setBackground(new Color(123, 134, 145, 83));
                    if (!panellogin1.isVisible() && !panellogin2.isVisible()) {
                        //Iddle 
                        Dashboard iddle = new Dashboard();
                        iddle.setVisible(true);
                        iddle.setPreviousFrame(this);
                        iddle.setAkun1(akun1);
                        iddle.setAkun2(akun2);
                        background.setVisible(false);

                        iddle.getPreviousFrame().setVisible(false);
                        this.setVisible(false);
                        clip.stop();
                    }
                } else {

                    JOptionPane.showMessageDialog(this, "Salah Password");
                
                
//                username1.setText("");
                pass1.setText("");
                }

            }
        }
    }//GEN-LAST:event_login1ActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // TODO add your handling code here:

        if (username2.getText().equalsIgnoreCase(player1)) {
            JOptionPane.showMessageDialog(panellogin1, "Akun ini sudah di pakai oleh user lain");

        } else {

            String username = username2.getText();
            String password = new String(pass2.getPassword());

            akun2 = new Account();

            akun2 = manager.getAccountByUsername(username);

            if (akun2 == null) {
                JOptionPane.showMessageDialog(this, "Salah username");
                
                username2.setText("");
                pass2.setText("");
            } else {
                if (password.equals(akun2.getPassword())) {
                    isPlayer2Login = true;
                    player2 = username;

                    panellogin2.setVisible(false);
                    panellogin2.setOpaque(false);
                    afterlogin2.setVisible(true);
                    afterlogin2.setBackground(new Color(123, 134, 145, 83));
                    if (!panellogin1.isVisible() && !panellogin2.isVisible()) {

                        Dashboard iddle = new Dashboard();
                        iddle.setVisible(true);
                        iddle.setPreviousFrame(this);
                        iddle.setAkun1(akun1);
                        iddle.setAkun2(akun2);
                        background.setVisible(false);
                        iddle.getPreviousFrame().setVisible(false);
                        this.setVisible(false);
                        clip.stop();
                    }
                } else {

                    JOptionPane.showMessageDialog(this, "Salah Password");
                
//                username1.setText("");
                pass2.setText("");
                }

            }
        }
    }//GEN-LAST:event_login2ActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:

        Register reg = new Register();
        this.setVisible(false);
        this.dispose();
        clip.stop();
        reg.setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        clip.stop();
        loadSound();
    }//GEN-LAST:event_formWindowActivated

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    int suaraControl = 0;
    private void soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soundMouseClicked
        // TODO add your handling code here:
        suaraControl++;

        if (suaraControl % 2 != 0) {
            clip.stop();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icon_x.png")));
        } else {
            loadSound();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icons_sound.png")));
        }
    }//GEN-LAST:event_soundMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NotifError_pass1;
    private javax.swing.JLabel NotifError_pass2;
    private javax.swing.JLabel NotifError_username1;
    private javax.swing.JLabel NotifError_username2;
    private javax.swing.JPanel afterlogin1;
    private javax.swing.JPanel afterlogin2;
    private javax.swing.JPanel background;
    private javax.swing.JPanel containerlogin1;
    private javax.swing.JPanel containerlogin2;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel lblMessage1;
    private javax.swing.JLabel lblMessage2;
    private javax.swing.JLabel lblNotAccount;
    private javax.swing.JLabel lbl_pass1;
    private javax.swing.JLabel lbl_pass2;
    private javax.swing.JLabel lbl_player1;
    private javax.swing.JLabel lbl_player2;
    private javax.swing.JLabel lbl_user1;
    private javax.swing.JLabel lbl_user2;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JLabel loading1;
    private javax.swing.JLabel loading2;
    private javax.swing.JButton login1;
    private javax.swing.JButton login2;
    private javax.swing.JPanel panellogin1;
    private javax.swing.JPanel panellogin2;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel register;
    private javax.swing.JLabel sound;
    private javax.swing.JTextField username1;
    private javax.swing.JTextField username2;
    // End of variables declaration//GEN-END:variables
}
