/*
 *     Name :  Iman Syahputra Situmorang
 *     NIM  :  11113064
 *     Date :  09/December/2014
 
 */
package View;

import Controller.DBManager;
import Model.Account;
//import Model.DataTable;
import Model.Monster;
import Model.MonsterAccount;
import Model.TemplateMonsterTable;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Takiya
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    Image image;
    private DBManager manager = null;
//    private DataTable tabel;
    private ArrayList<ImageIcon> iconList = null;

    public Register() {
        setUndecorated(true);
        image = new ImageIcon(getClass().getResource("/Images/Background/tiga.jpg")).getImage();
        initComponents();
//        tabel = new DataTable();
        manager = new DBManager();
        iconList = new ArrayList<ImageIcon>();
        this.loadData();
        PanelRegister1.setOpaque(false);
        PanelRegister2.setOpaque(false);

    }

    AudioClip clip;

    public void loadSound() {

        URL url = getClass().getResource("/Sound/Register.wav");
        clip = Applet.newAudioClip(url);
//        AudioClip clip2 = Applet.newAudioClip(url);
        clip.play();
        clip.loop();
    }

    public void loadData() {
        Object[] coloumnNames = {"Monster", "Name", "AP", "HP", "DP", "ID"};
        ArrayList<Monster> monster = new ArrayList<Monster>();
        ArrayList<ImageIcon> icon = new ArrayList<ImageIcon>();
        monster = manager.loadMonster();
        ImageIcon monIcon = null;
        for (int i = 0; i < monster.size(); i++) {
//            System.out.println(monster.get(i).getName());
            monIcon = new ImageIcon(getClass().getResource("/Images/Monster/Monster_mini/" + monster.get(i).getAvatarUrl()));
            icon.add(monIcon);

        }

        int numOfMonsters = monster.size();
        Object data1[][] = new Object[numOfMonsters][6];
        for (int i = 0; i < numOfMonsters; i++) {
            data1[i][0] = icon.get(i);
            data1[i][1] = monster.get(i).getName();
            data1[i][2] = monster.get(i).getAp();
            data1[i][3] = monster.get(i).getHp();
            data1[i][4] = monster.get(i).getDp();
            data1[i][5] = monster.get(i).getId();

        }

        TemplateMonsterTable dtTable = new TemplateMonsterTable(data1, coloumnNames);
        this.tableMonster.setModel(dtTable);
        this.tableMonster.setRowHeight(100);

        tableMonster.removeColumn(tableMonster.getColumnModel().getColumn(5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new PanelBackground(image);
        ;
        PanelRegister1 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        lbl_welcome = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        PanelRegister2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMonster = new javax.swing.JTable();
        exit = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setPreferredSize(new java.awt.Dimension(1366, 768));

        PanelRegister1.setPreferredSize(new java.awt.Dimension(400, 500));

        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_username.setText("Username");

        lbl_password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_password.setText("Password");

        lbl_welcome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/header.png"))); // NOI18N

        javax.swing.GroupLayout PanelRegister1Layout = new javax.swing.GroupLayout(PanelRegister1);
        PanelRegister1.setLayout(PanelRegister1Layout);
        PanelRegister1Layout.setHorizontalGroup(
            PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegister1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegister1Layout.createSequentialGroup()
                        .addGroup(PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_username)
                            .addComponent(lbl_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(password)))
                    .addGroup(PanelRegister1Layout.createSequentialGroup()
                        .addComponent(lbl_welcome)
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelRegister1Layout.setVerticalGroup(
            PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegister1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_username)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(PanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password))
                .addGap(26, 26, 26)
                .addComponent(lbl_welcome)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        Register.setText("Finish Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/Back1.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        PanelRegister2.setPreferredSize(new java.awt.Dimension(700, 500));

        tableMonster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableMonster.setToolTipText("");
        jScrollPane1.setViewportView(tableMonster);

        javax.swing.GroupLayout PanelRegister2Layout = new javax.swing.GroupLayout(PanelRegister2);
        PanelRegister2.setLayout(PanelRegister2Layout);
        PanelRegister2Layout.setHorizontalGroup(
            PanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegister2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRegister2Layout.setVerticalGroup(
            PanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegister2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/icons_sound.png"))); // NOI18N
        sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(PanelRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sound)
                    .addComponent(exit))
                .addGap(63, 63, 63)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        String username = this.username.getText();
        String password = new String(this.password.getPassword());
        // System.out.println("apakah kosong" + username.isEmpty());

        int akun_id = 0;
        Account akun_baru = new Account();

        int rowSelected = -1;
        rowSelected = tableMonster.getSelectedRow();
        if (!username.isEmpty() && !password.isEmpty()) {

//            System.out.println("apakah kosong " + username.isEmpty());
            akun_baru = manager.getAccountByUsername(username);
            if (akun_baru == null) {

                Account akun = new Account(username, password);

                if (rowSelected != -1) {
                    manager.createAccount(akun);

                    akun_baru = new Account();

                    akun_baru = manager.getAccountByUsername(username);
                    try {
                        akun_id = akun_baru.getId();
                    } catch (NullPointerException ex) {
                        akun_id = 0;
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Choose the Monster");
                }
            } else {

                JOptionPane.showMessageDialog(null, "This Username already registered try another username");

                this.username.setText("");
                this.password.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please  fill the username/password");

        }

        if (akun_id == 0) {

//            JOptionPane.showMessageDialog(null, "Please  fill the username/password");
        } else {
//            JOptionPane.showMessageDialog(null, "Succesfull");
//            System.out.println("akun_id= " + akun_id);

            rowSelected = this.tableMonster.getSelectedRow();

            if (rowSelected != -1) {
                String datamonster = this.tableMonster.getModel().getValueAt(rowSelected, 5).toString();
//                String datamonster = this.tableMonster.getClass().
//                System.out.println("datamonster " + datamonster);
                Monster momon = manager.findById(Integer.parseInt(datamonster));
                String monster_name = momon.getName();
//                int monster_id = momon.getId();
                int monster_hp = momon.getHp();
                int monster_ap = momon.getAp();
                int monster_dp = momon.getDp();
                int monster_winPoint = 0;
                int monster_coin = 0;

                //MonsterAccount akun_monster = new MonsterAccount(akun_id, monster_id, monster_name, monster_hp, monster_ap, monster_dp, monster_winPoint, monster_coin);
                MonsterAccount akun_monster = new MonsterAccount(akun_baru, momon, monster_name, monster_hp, monster_ap, monster_dp, monster_winPoint, monster_coin);

                manager.createMonsterAccount(akun_monster);

                JOptionPane.showMessageDialog(null, "Berhasil");
                this.setVisible(false);

                Login login = new Login();
                login.setVisible(true);
                clip.stop();
            }
        }

    }//GEN-LAST:event_RegisterActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        clip.stop();
        (new Login()).setVisible(true);
        
    }//GEN-LAST:event_backMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loadSound();
    }//GEN-LAST:event_formWindowActivated
    int suaraControl = 0;
    private void soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soundMouseClicked
        // TODO add your handling code here:
        suaraControl++;

        if (suaraControl % 2 != 0) {
            clip.stop();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icon_x.png")));
        } else {
            loadSound();
            sound.setIcon(new ImageIcon(getClass().getResource("/Images/Background/icons_sound.png")));
        }
    }//GEN-LAST:event_soundMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel PanelRegister1;
    private javax.swing.JPanel PanelRegister2;
    private javax.swing.JButton Register;
    private javax.swing.JLabel back;
    private javax.swing.JLabel exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel sound;
    private javax.swing.JTable tableMonster;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
